# Generated by Django 5.0.4 on 2026-05-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="learner",
            name="familiar_region",
            field=models.CharField(
                blank=True,
                help_text="Used for localized examples",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learner",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("EN", "English"),
                    ("LG", "Luganda"),
                    ("SW", "Swahili"),
                    ("RN", "Runyankole"),
                ],
                default="EN",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="learner",
            name="preferred_methodology",
            field=models.CharField(
                choices=[
                    ("SOCRATIC", "Socratic (Questioning)"),
                    ("DIRECT", "Direct Instruction"),
                    ("VISUAL", "Visual & Storytelling"),
                    ("PROJECT", "Project-Based"),
                ],
                default="SOCRATIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="learner",
            name="preferred_subjects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of subjects the learner focuses on",
            ),
        ),
        migrations.AddField(
            model_name="learner",
            name="theme",
            field=models.CharField(
                choices=[("LIGHT", "Light"), ("DARK", "Dark"), ("SYSTEM", "System")],
                default="SYSTEM",
                max_length=10,
            ),
        ),
    ]
