# Generated by Django 5.2.13 on 2026-04-15 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField(blank=True, null=True)),
                (
                    "flagged_out_of_scope",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("kb_version", models.CharField(default="MVP-1.0", max_length=20)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
