# Generated by Django 5.0.4 on 2026-05-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tutor", "0001_initial"),
        ("curriculum", "0002_lesson_image_lesson_video_file_lesson_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisession",
            name="context_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="The lesson the learner was viewing when this question was asked.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_sessions",
                to="curriculum.lesson",
            ),
        ),
        migrations.AddField(
            model_name="aisession",
            name="llm_provider_used",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which LLM provider won the race (gemini-1.5-flash, deepseek-chat, claude-3-5-haiku, mock).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="aisession",
            name="tool_calls_log",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Log of MCP tool calls made by the agent during this session.",
            ),
        ),
        migrations.AlterField(
            model_name="aisession",
            name="kb_version",
            field=models.CharField(default="MCP-1.0", max_length=20),
        ),
    ]
