# Generated by Django 5.2.13 on 2026-04-15 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level_name",
                    models.CharField(
                        choices=[
                            ("S1", "S1"),
                            ("S2", "S2"),
                            ("S3", "S3"),
                            ("S4", "S4"),
                            ("S5", "S5"),
                            ("S6", "S6"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("sort_order", models.SmallIntegerField(db_index=True)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("competency_name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencies",
                        to="curriculum.level",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencies",
                        to="curriculum.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("LESSON", "Lesson"), ("MATERIAL", "Material")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="NCDC", max_length=50)),
                ("is_downloadable", models.BooleanField(db_index=True, default=True)),
                ("file_size_kb", models.IntegerField(blank=True, null=True)),
                ("body_html", models.TextField(blank=True)),
                (
                    "competencies",
                    models.ManyToManyField(
                        related_name="%(class)ss", to="curriculum.competency"
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="curriculum.level",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="curriculum.subject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
