# Generated by Django 5.0.4 on 2026-04-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Supporting image for the lesson",
                null=True,
                upload_to="curriculum/images/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Direct video upload",
                null=True,
                upload_to="curriculum/videos/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="Link to video content", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="body_html",
            field=models.TextField(blank=True, help_text="Supporting text content"),
        ),
    ]
