# Generated by Django 5.2.13 on 2026-05-09 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_lesson_image_lesson_video_file_lesson_video_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF / Textbook"),
                            ("IMAGE", "Image / Illustration"),
                            ("AUDIO", "Audio Recording"),
                            ("MAP", "Map / Geography"),
                            ("VIDEO", "Video"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded to Cloudflare R2", upload_to="library/"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated topic tags",
                        max_length=500,
                    ),
                ),
                (
                    "is_indexed",
                    models.BooleanField(
                        default=False,
                        help_text="True after ChromaDB embedding is built",
                    ),
                ),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="Publisher, NCDC, etc.", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "class_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_files",
                        to="curriculum.level",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_files",
                        to="curriculum.subject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Library File",
                "verbose_name_plural": "Library Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("source_url", models.URLField(max_length=500)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "content",
                    models.TextField(
                        help_text="Scraped/summarised content from the web"
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0, help_text="0.0–1.0 CBC relevance score from LLM"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "auto_approved",
                    models.BooleanField(
                        default=False,
                        help_text="True if auto-approved by relevance threshold",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.level",
                    ),
                ),
                (
                    "library_file",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_source",
                        to="curriculum.curriculumfile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Entry",
                "verbose_name_plural": "Research Entries",
                "ordering": ["-relevance_score", "-created_at"],
            },
        ),
    ]
