# Generated by Django 5.2.13 on 2026-05-13 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_library_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("SUBJECT", "Subject"),
                            ("COMPETENCY", "Competency"),
                            ("LESSON", "Lesson"),
                            ("CONCEPT", "Concept"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "chroma_doc_id",
                    models.CharField(
                        blank=True,
                        help_text="Links to ChromaDB vector document",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Curriculum Node",
                "verbose_name_plural": "Curriculum Nodes",
            },
        ),
        migrations.CreateModel(
            name="CurriculumEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("REQUIRES", "Requires / Prerequisite"),
                            ("BELONGS_TO", "Belongs To"),
                            ("TEACHES", "Teaches"),
                            ("RELATES_TO", "Relates To"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Strength or importance of this relationship",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="curriculum.curriculumnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="curriculum.curriculumnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum Edge",
                "verbose_name_plural": "Curriculum Edges",
                "unique_together": {("source", "target", "relationship")},
            },
        ),
    ]
