# Generated by Django 5.0.4 on 2026-04-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo upload",
                null=True,
                upload_to="feed/photos/",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional video upload",
                null=True,
                upload_to="feed/videos/",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video_description",
            field=models.TextField(blank=True, help_text="Description for the video"),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="type",
            field=models.CharField(
                choices=[("LIKE", "❤️"), ("SHARE", "🔃")], db_index=True, max_length=20
            ),
        ),
    ]
